"""
MASVS Audit Copilot — Markdown Report Exporter
Generates Markdown audit reports for wikis, Jira tickets, and documentation.
"""

from datetime import datetime, timezone
from typing import List


def generate_markdown_report(
    scan_data: dict,
    findings: list,
    output_path: str,
) -> str:
    """
    Generate a Markdown audit report.

    Args:
        scan_data: Scan metadata.
        findings: List of finding dictionaries.
        output_path: Path to save the Markdown file.

    Returns:
        Path to the generated file.
    """
    from app.mapping.masvs_mapper import MASVS_CATEGORIES

    lines = []

    # ─── Header ───
    lines.append(f"# 🛡️ Security Audit Report")
    lines.append(f"")
    lines.append(f"**Application:** {scan_data.get('file_name', 'Unknown')}")
    lines.append(f"**Scan Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Score:** {scan_data.get('score', 0):.1f} / 100 ({scan_data.get('grade', '?')})")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")

    # ─── Summary ───
    lines.append(f"## 📊 Executive Summary")
    lines.append(f"")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info")
        if sev in severity_counts:
            severity_counts[sev] += 1

    for sev, count in severity_counts.items():
        emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}.get(sev, "")
        lines.append(f"| {emoji} {sev.capitalize()} | {count} |")

    lines.append(f"| **Total** | **{len(findings)}** |")
    lines.append(f"")

    # ─── MASVS Category Breakdown ───
    lines.append(f"## 📋 MASVS Category Breakdown")
    lines.append(f"")
    lines.append(f"| Category | Name | Findings |")
    lines.append(f"|----------|------|----------|")

    for cat_id, cat_name in MASVS_CATEGORIES.items():
        count = sum(1 for f in findings if f.get("masvs_category") == cat_id)
        lines.append(f"| `{cat_id}` | {cat_name} | {count} |")

    lines.append(f"")

    # ─── Findings ───
    lines.append(f"## 🔍 Detailed Findings")
    lines.append(f"")

    for i, finding in enumerate(findings, 1):
        severity = finding.get("severity", "info")
        emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}.get(severity, "")

        lines.append(f"### {emoji} #{finding.get('id', i)} — {finding.get('title', 'Unknown')}")
        lines.append(f"")
        lines.append(f"- **Severity:** {severity.upper()}")
        lines.append(f"- **MASVS Control:** `{finding.get('masvs_control', 'N/A')}`")
        lines.append(f"- **CVSS Score:** {finding.get('cvss_score', 'N/A')} (`{finding.get('cvss_vector', 'N/A')}`)")
        lines.append(f"- **Status:** {finding.get('triage_result', 'not_triaged')}")

        if finding.get("affected_file"):
            lines.append(f"- **Affected File:** `{finding['affected_file']}`")

        lines.append(f"")

        if finding.get("description"):
            lines.append(f"**Description:** {finding['description']}")
            lines.append(f"")

        if finding.get("affected_code"):
            lines.append(f"**Vulnerable Code:**")
            lines.append(f"```")
            lines.append(finding["affected_code"])
            lines.append(f"```")
            lines.append(f"")

        if finding.get("triage_justification"):
            lines.append(f"**AI Triage:** {finding['triage_justification']}")
            lines.append(f"")

        if finding.get("remediation_code"):
            lines.append(f"**Recommended Fix:**")
            if finding.get("remediation_description"):
                lines.append(f"{finding['remediation_description']}")
            lines.append(f"```")
            lines.append(finding["remediation_code"])
            lines.append(f"```")
            lines.append(f"")

        lines.append(f"---")
        lines.append(f"")

    # ─── Footer ───
    lines.append(f"*Generated by MASVS Audit Copilot — Based on OWASP MASVS v2 & MASTG*")

    content = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path
